### ISSUE TITLE
C.H.I.P. buildroot does not produce sunxi-spl-with-ecc.bin

### ISSUE THREAD

**Issue by zendes** [NextThingCo/CHIP-buildroot#8]
See https://bbs.nextthing.co/t/c-h-i-p-buildroot-does-not-produce-sunxi-spl-with-ecc-bin/1621

I'm experiencing the same issue as the original poster: make chip_defconfig && make does not build sunxi-spl-with-ecc.bin in output/images:

ls -1 output/images
rootfs.cpio
rootfs.tar
rootfs.ubi
rootfs.ubifs
rootfs.ubifs.lzo
sun5i-r8-chip.dtb
sunxi-spl.bin
u-boot-dtb.bin
uboot-env.bin
zImage

**Comment by e-yes** [comment]
+1

**Comment by jasonabele** [comment]
If you are building with the nextthing/4.4/next branch in buildroot, the sunxi-spl-with-ecc.bin is produced when uboot compiles.  It can be found in:

$BUILDROOT_DIR/output/build/uboot-*/spl/sunxi-spl-with-ecc.bin

So as a work-around, you can copy it from there.  I agree that it is annoying to not have it appear in $BUILDROOT/output/images ... I will see if we can get  a fix posted.  Thanks for your patience.

**Comment by jasonabele** [comment]
Fix was merged https://github.com/NextThingCo/CHIP-buildroot/commit/9492cfa621b70c03a52eec432466f16d2b88d463

**Comment by e-yes** [comment]
Thanks, unfortunately it doesn't solve the problem.
```bash
  MKIMAGE u-boot.img
  LD      spl/lib/built-in.o
  LD      spl/u-boot-spl
  OBJCOPY spl/u-boot-spl.bin
  MKSUNXI spl/sunxi-spl.bin
  COPY    u-boot.dtb
  CAT     u-boot-dtb.bin
  MKIMAGE u-boot-dtb.img
  CAT     u-boot-sunxi-with-spl.bin
>>> uboot chip_stable Installing to target
>>> uboot chip_stable Installing to images directory
cp -dpf /home/vagrant/CHIP-buildroot/output/build/uboot-chip_stable/u-boot-dtb.bin /home/vagrant/CHIP-buildroot/output/images/
for p in spl/sunxi-spl.bin spl/sunxi-spl-with-ecc.bin; do cp -dpf /home/vagrant/CHIP-buildroot/output/build/uboot-chip_stable/$p /home/vagrant/CHIP-buildroot/output/images/; done
cp: cannot stat ‘/home/vagrant/CHIP-buildroot/output/build/uboot-chip_stable/spl/sunxi-spl-with-ecc.bin’: No such file or directory
make[1]: *** [/home/vagrant/CHIP-buildroot/output/build/uboot-chip_stable/.stamp_images_installed] Error 1
make: *** [_all] Error 2
```

Also, I couldn't find "nextthing/4.4/next" branch you mentioned above:
```bash
vagrant@vagrant-ubuntu-trusty-32:~/CHIP-buildroot$ git branch -r
  origin/HEAD -> origin/chip/stable
  origin/at/2015.08/overlays
  origin/bb/chip-nand
  origin/bb/chip-nand-slc-mode
  origin/bb/chip-nand-slc-mode-perf
  origin/bb/env-in-ubi
  origin/by/mali
  origin/by/nextthing/2015.08/next
  origin/chip/bugfix
  origin/chip/next
  origin/chip/splash
  origin/chip/stable
  origin/fix_linaro_https_urls
  origin/fix_missing_sunxi_spl_with_ecc
  origin/hwtest
  origin/ja/deb-pkg
  origin/ja/nextthing/2015.08/next
  origin/ja/ntc/2015.08/next
  origin/mr/fastboot-nand
  origin/nextthing/2015.08/chip
  origin/nextthing/2015.08/next
  origin/nextthing/chip-nand
  origin/nextthing/khb
  origin/ntc/2015.08/next
  origin/ww/develop
  origin/ww/hwtest
  origin/ww/tooling

```
Could you clarify which branch I should use?

**Comment by jasonabele** [comment]
Looks like you have a fairly old branch list, to get the latest branches, consider trying:

> git remote update origin

If you want to work with the old chip/stable branch, just change the 

> BR2_TARGET_UBOOT_SPL_NAME="spl/sunxi-spl*.bin"

in your .config file (or in config/chip_defconfig and re-run "make chip_defconfig"), but I do not know if the uboot version built with chip/stable branch actually builds the spl-with-ecc.bin

**Comment by jasonabele** [comment]
oops, read that too fast ... the branch you want in CHIP-buildroot is nextthing/2015.08/next ... sorry for the confusion

**Comment by e-yes** [comment]
I use nextthing/2015.08/next now. Just to be fair, I used old config (with changes from https://github.com/NextThingCo/CHIP-buildroot/commit/9492cfa621b70c03a52eec432466f16d2b88d463). Now I'm trying to make full build with brand new config (make chip_defconfig && make).
BTW, hwtest build is broken, so I disabled it in configuration.

**Comment by e-yes** [comment]
I destroyed VM, created it up from scratch (Vagrant up), disabled HWTest, make chip_defconfig && make, build finished without any problems.
Now I'm trying to flash, it resulting to the similar problem:
```shell
vagrant@vagrant-ubuntu-trusty-32:~/CHIP-tools$ sudo BUILDROOT_OUTPUT_DIR=../CHIP-buildroot/output ./chip-fel-flash.sh
BUILDROOT_OUTPUT_DIR = ../CHIP-buildroot/output
== preparing images ==
ERROR: can not read ../CHIP-buildroot/output/images/sunxi-spl-with-ecc.bin
vagrant@vagrant-ubuntu-trusty-32:~/CHIP-tools$ ll ../CHIP-buildroot/output/images/*ecc*
ls: cannot access ../CHIP-buildroot/output/images/*ecc*: No such file or directory

```

**Comment by bakroistvan** [comment]
+1
